server:
  port: 8099
spring:
   application:
        name: gateway-service
   cloud:
      gateway:
         routes:
           - id: service-product
             uri: lb://service-product
             predicates:
              - Path=/product/**
     
           