server:
  port: 8099
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
      - id: service-product
        uri: lb://service-product
        predicates:
        - Path=/product/**
managment:
  edpoints:
    web:
      exposure:
        include: '*'