server:
  port: 0
spring:
  application:
    name: service-product
  data:
    mongodb:
      database: Banca
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'